name: BankNotes
main: AndreasHGK\BankNotes\BankNotes
version: 2.0.3
api: [3.7.0]
load: POSTWORLD
author: AndreasHGK
description: A plugin that makes money into an item to trade with!
depend: ["EconomyAPI"]

commands:
 makenote:
  description: "Withdraw money and put it on a bank note"
  usage: "/makenote {value} [count]"
  permission: banknotes.get
  aliases: ["note"]
 banknotes:
  description: "plugin commands"
  usage: "/banknotes <subcommand>"
  permission: banknotes.command
 depositnote:
  description: "Deposit a note to your account"
  usage: "/depositnote"
  permission: banknotes.deposit

permissions:
 banknotes:
  default: false
  description: "bankNotes root permission"
  children:
   banknotes.get:
    default: true
    description: "allow players to withdraw banknotes"
   banknotes.deposit:
    default: true
    description: "allow players to deposit banknotes"
   banknotes.command:
    default: true
    description: "plugin commands like /banknotes check"
   banknotes.command.admin:
    default: false
    description: "admin commands like /banknotes admin reload,validate,devalidate"
